dist: xenial
sudo: required
language:
  - generic
cache:
  - apt
services:
  - docker

env:
  - DISTR=indigo  BASEIMG=ros:indigo-robot
  - DISTR=kinetic BASEIMG=ros:kinetic-robot
  - DISTR=melodic BASEIMG=ros:melodic-robot
  
before_script:
  - docker pull ${BASEIMG}

script:
  - docker build -f Dockerfile.${DISTR} --tag ros:aero_${DISTR} --build-arg RUN_TESTS=true .
 
matrix:
  allow_failures:
    - env: DISTR=indigo  BASEIMG=ros:indigo-robot
    - env: DISTR=melodic BASEIMG=ros:melodic-robot
     
