controller_list:
  - name: rhand_controller
    joints:
      - r_wrist_r_joint
      - r_indexbase_joint
      - r_indexmid_joint
      - r_indexend_joint
      - r_thumb_joint
  - name: rarm_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r_shoulder_p_joint
      - r_shoulder_y_joint
      - r_elbow_joint
      - r_wrist_y_joint
      - r_wrist_p_joint
      - r_wrist_r_joint
      - r_hand_y_joint
  - name: lifter_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - virtual_lifter_x_joint
      - virtual_lifter_z_joint

