# common
### ps button is reset pose (upper body only unless RB pressed)
reset_pose_button: 16
### start button switches to basic mode
switch_basic_mode: 3
### select button switches to joint mode
switch_mode: 0

### triangle button press disables button and axes during basic mode
external_command: 12


# basic mode
## teleop-twist
### left stick for linear, right for angular
axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.4
  y: 0.4
axis_angular:
  yaw: 2
scale_angular:
  yaw: 0.5
### use L1 to enable teleop
enable_button: 10
enable_turbo_button: -1
## other basic functions
### use circle for right grasp, rectangle for left grasp
grasp_button:
  R: 13
### use L2, R2 for setting grasp angle
grasp_angle_axis:
  R: 9
min_grasp_angle:
  R: -1.0
range_grasp_angle:
  R: 2.0
### use X to open grasp
enable_grasp_angle: 14
### left stick for upward, right for forward
lifter_axis:
  x: 2
  z: 3
scale_lifter:
  x: 0.005
  z: 0.005
### use R1 to enable lifter
enable_lifter: 11

# joint mode
### the names do not correspond to actual joint names
### all pitch are direction pad up/down
### yaws are mostly direction stick
### roll or some yaws are direction pad left/right
## shoulder
shoulder:
  pitchp: 4
  pitchm: 6
  ### use left stick for yaw
  yaw: 0
  ### use R1 to trigger upper arm
  enable_right: 11
scale_shoulder:
  pitch: -0.05
  yaw: 0.06
## elbow
elbow:
  pitchp: 4
  pitchm: 6
  yawp: 7
  yawm: 5
  ### use R2 to trigger forearm
  enable_right: 9
scale_elbow:
  yaw: 0.05
  pitch: 0.05
## wrist
wrist:
  pitchp: 4
  pitchm: 6
  ### use circle, rectangle to trigger wrist
  enable_right: 15
scale_wrist:
  yaw: 0.03
  pitch: 0.05
## ik
ik:
  x: 1
  y: 0
  z: 3
  enable_right: 8
scale_ik:
  x: 0.01
  y: 0.01
  z: 0.01
